name: CrowdsourcingPlatform

on:
  push:
    branches: [ "main" ]        
  pull_request:
    branches: [ "main" ]        

jobs:
  build:
    runs-on: ${{ matrix.os }}   
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] 

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'   
    - name: Restore dependencies
      run: dotnet restore TestFuel/CrowdsourcingPlatform.sln

    - name: Build project
run: dotnet build TestFuel/CrowdsourcingPlatform.sln --no-restore -c Release
